############################################################
# +------------------------------------------------------+ #
# |                        BotApi                        | #
# +------------------------------------------------------+ #
############################################################

api-token: MFA9KrEpdBj8YMsJFJID6ib7lR4HFHd9